// Generated by schemas/input/scripts/generate-validation-body.ts from schemas/input/validation-body/*.yaml.
// Do not edit this file by hand.

import type { SourcedClaim } from "./source-ref.generated.js";

/** 当前验证的 BDD 事实投影；只承载 BDD identity、Given/When/Then 与对 Planner 有用的场景约束。 */
export interface BddFact {
  /** BDD fact 稳定 ID。 */
  fact_id: string;
  /** 固定为 bdd_fact。 */
  fact_type: "bdd_fact";
  /** BDD 场景稳定 ID。 */
  scenario_id: string;
  /** 除 Given / When / Then 之外仍会影响 Planner 的 BDD 场景 claim；没有明确来源或用途时不要填写。 */
  claims?: SourcedClaim[];
  /** BDD Given 语义；每个步骤都必须是带来源 claim。 */
  given: SourcedClaim[];
  /** BDD When 语义；每个步骤都必须是带来源 claim。 */
  when: SourcedClaim[];
  /** BDD Then 语义；每个步骤都必须是带来源 claim。 */
  then: SourcedClaim[];
}
