// Generated by schemas/input/scripts/generate-validation-body.ts from schemas/input/validation-body/*.yaml.
// Do not edit this file by hand.

import type { SourcedClaim } from "./source-ref.generated.js";
import type { BddFact } from "./bdd-fact.generated.js";
import type { CapabilityFact } from "./capability-fact.generated.js";
import type { RequirementFact } from "./requirement-fact.generated.js";
import type { SpecificationFact } from "./specification-fact.generated.js";
import type { FeatureFact } from "./feature-fact.generated.js";
import type { ImplementationFact } from "./implementation-fact.generated.js";

export interface ValidationCatalogRef {
  /** 与本 ValidationBody 配套的 catalog ID；只要求在当前 run 内稳定。 */
  catalog_id: string;
  /** catalog JSON 的本地路径、运行时 URI 或相对路径。 */
  uri: string;
  /** 可选内容摘要；用于需要时校验 catalog 未漂移。 */
  digest?: string;
}

/** 当前 BDD 的验收口径；只写有证据、有意义、会影响 Planner 判断的条件。 */
export interface AcceptanceCriteria {
  /** 满足哪些明确条件才算验证通过；没有明确依据时不要填写。 */
  pass_conditions?: SourcedClaim[];
  /** 出现哪些明确条件应判定为失败；没有明确依据时不要填写。 */
  fail_conditions?: SourcedClaim[];
  /** 哪些情况下不能判定通过；只记录已确认的证据不足条件。 */
  insufficient_evidence_conditions?: SourcedClaim[];
}

export interface ValidationBody {
  /** 本次 run 内部 Validation Body ID；用于 run 内追踪和历史归类，不作为跨 run 业务身份。 */
  validationBodyId: string;
  /** 固定类型标识，表示这是 Scout 内部的 Validation Body。 */
  bodyType: "validation_body";
  /** 生成该 ValidationBody 的 run ID。 */
  runId: string;
  /** 该 ValidationBody 创建时间。 */
  createdAt: string;
  /** 本 ValidationBody 配套的 run 内引用目录；所有 source_ref_ids 和 evidence_ref_ids 都必须在该 catalog 中解析。 */
  catalog_ref: ValidationCatalogRef;
  /** BDD 事实；承载当前 BDD 的 Given / When / Then 和场景身份。 */
  bdd_fact: BddFact;
  /** 当前 BDD 相关的需求意图和验收口径；只保留会影响 Planner 的 claim。 */
  requirement_facts?: RequirementFact[];
  /** 当前 BDD 相关的设计承诺和规格约束；只保留会影响 Planner 的 claim。 */
  specification_facts?: SpecificationFact[];
  /** 当前 BDD 相关的 synaptic proposal 事实；只保留 proposal 中会影响 Planner 的 claim。 */
  feature_facts?: FeatureFact[];
  /** 当前 BDD 相关的生产实现覆盖；只保留经过源码真实性校验的 claim。 */
  implementation_facts?: ImplementationFact[];
  /** 当前 BDD 条件下的 capability 摘要投影；只保留对 Plan 有用的信息。 */
  capability_facts?: CapabilityFact[];
  /** 本次验证的通过、失败和证据不足条件；不要为了填满字段编造。 */
  acceptance_criteria?: AcceptanceCriteria;
  /** 从 bdd_fact.given[].text 投影出的 Given 文本，供 Planner 快速读取。 */
  given: string[];
  /** 从 bdd_fact.when[].text 投影出的 When 文本，供 Planner 快速读取。 */
  when: string[];
  /** 从 bdd_fact.then[].text 投影出的 Then 文本，供 Planner 快速读取。 */
  then: string[];
  /** 输入材料中明确限制执行、判断、资源、环境或安全边界的约束。 */
  constraints?: SourcedClaim[];
  /** 输入中缺失、矛盾、不可观测或需要人工处理的不确定项。 */
  uncertainty_items?: SourcedClaim[];
}
