// Generated by schemas/input/scripts/generate-validation-body.ts from schemas/input/validation-body/*.yaml.
// Do not edit this file by hand.

import type { SourcedClaim } from "./source-ref.generated.js";

/** 当前 BDD 条件下的 capability 摘要投影；只保留对 Plan 有用的信息，不复刻 hippocampus capability 对象。 */
export interface CapabilityFact {
  /** capability fact 稳定 ID，建议包含 BDD scenario 与来源 capability。 */
  fact_id: string;
  /** 固定为 capability_fact。 */
  fact_type: "capability_fact";
  /** 该 capability fact 直接服务的 BDD 场景 ID。 */
  relevant_bdd_refs: string[];
  /** 对当前 BDD 有用的 capability 事实；每一句都必须可追溯到具体来源。 */
  claims: SourcedClaim[];
  /** 已遍历但不进入 Planner 主上下文的 capability/synaptic/knowledge 信息及排除原因。 */
  excluded_context?: SourcedClaim[];
}
