// Generated by schemas/input/scripts/generate-validation-body.ts from schemas/input/validation-body/*.yaml.
// Do not edit this file by hand.

import type { AssetSourceRef, EvidenceRef, SourceLocator } from "./source-ref.generated.js";

/** ValidationCatalog 的实现定位注册项；只记录生产源码、配置、符号或 artifact 的可定位引用，不承载 Planner 语义。 */
export interface ImplementationRef {
  /** 实现定位 run 内 ID；用于把 implementation fact 中的生产实现 claim 追溯到可定位源码或 artifact。 */
  implementation_ref_id: string;
  /** 定位类型，例如模块、源码路径、配置、API、事件、callback、schema、asset 或符号。 */
  kind: "module" | "source_path" | "config" | "api" | "event" | "callback" | "schema" | "asset" | "symbol";
  /** 实现定位引用，例如模块名、源码路径、API 名称、事件名、symbol 或 asset path。 */
  ref: string;
  /** 可选本地路径、运行时 URI、知识库 URI 或外部 URL；当 ref 不足以定位时必须提供。 */
  uri?: string;
  /** 可选来源内具体定位，例如 symbol、line_range、json_path 或 file。 */
  locator?: SourceLocator;
  /** 支撑该实现定位的 SourceRef ID 列表。 */
  source_ref_ids: string[];
}

/** ValidationBody 的 run 内来源与证据目录；承载 SourceRef/EvidenceRef 注册表，不承载 Planner 事实。 */
export interface ValidationCatalog {
  /** 本次 run 内部 catalog ID；只要求在当前 run 内稳定，不作为跨 run 身份。 */
  catalog_id: string;
  /** 固定类型标识，表示这是 ValidationBody 配套的引用目录。 */
  catalogType: "validation_catalog";
  /** 生成该 catalog 的 run ID。 */
  runId: string;
  /** 该 catalog 创建时间。 */
  createdAt: string;
  /** 本 catalog 的来源注册表；所有 claim 必须引用这里的 source_ref_id。 */
  source_refs: AssetSourceRef[];
  /** 本 catalog 的证据注册表；历史证据只作为计划输入，不替代当前 run 证据。 */
  evidence_refs: EvidenceRef[];
  /** 本 catalog 的实现定位注册表；只记录定位，不记录 Planner 决策语义。 */
  implementation_refs: ImplementationRef[];
}
