// Generated by schemas/input/scripts/generate-validation-body.ts from schemas/input/validation-body/*.yaml.
// Do not edit this file by hand.

import type { SourcedClaim } from "./source-ref.generated.js";

/** 当前 BDD 相关的 synaptic proposal 事实投影；只保留 proposal 中会影响 Planner 的需求背景、目标、范围和非目标。 */
export interface FeatureFact {
  /** feature fact 稳定 ID。 */
  fact_id: string;
  /** 固定为 feature_fact。 */
  fact_type: "feature_fact";
  /** proposal 的动机、目标、范围、非目标、用户价值和与当前 BDD 的关系 claim。 */
  claims: SourcedClaim[];
}
