// Generated by schemas/input/scripts/generate-validation-body.ts from schemas/input/validation-body/*.yaml.
// Do not edit this file by hand.

import type { SourcedClaim } from "./source-ref.generated.js";

/** 当前 BDD 相关的生产实现覆盖投影；只记录已通过 CodeGraph 或合规 rg 回退校验的生产源码、配置、API、symbol 或 artifact 事实。 */
export interface ImplementationFact {
  /** implementation fact 稳定 ID。 */
  fact_id: string;
  /** 固定为 implementation_fact。 */
  fact_type: "implementation_fact";
  /** 当前 BDD 对应实现覆盖状态；必须由 claim 与 evidence 支撑。 */
  coverage_status: "covered" | "partial" | "missing" | "out_of_scope";
  /** 生产实现覆盖、源码/API/配置/artifact、历史 gap 与当前验证影响的 claim；不得纳入测试代码。 */
  claims: SourcedClaim[];
}
