// Generated by schemas/input/scripts/generate-validation-body.ts from schemas/input/validation-body/*.yaml.
// Do not edit this file by hand.

import type { SourcedClaim } from "./source-ref.generated.js";

/** 当前 BDD 相关的需求、规格或 feature 意图投影；只保留 Planner 判断验证目标和验收口径所需的信息。 */
export interface RequirementFact {
  /** requirement fact 稳定 ID。 */
  fact_id: string;
  /** 固定为 requirement_fact。 */
  fact_type: "requirement_fact";
  /** 需求意图、验收口径、当前 BDD 覆盖范围和不覆盖范围的 claim。 */
  claims: SourcedClaim[];
}
