// Generated by schemas/input/scripts/generate-validation-body.ts from schemas/input/validation-body/*.yaml.
// Do not edit this file by hand.


export interface SourceLocator {
  /** 来源定位类型，用于把来源具体到字段、段落、表格行、符号、JSON 路径、文件或用户确认。 */
  kind: "frontmatter" | "heading" | "line_range" | "table_row" | "symbol" | "json_path" | "file" | "user_confirmation" | "other";
  /** 来源定位值，例如 frontmatter:scenario_id、heading:Given、line_range:31-38、symbol:ConsentManager.RequestAgeSignals。 */
  value: string;
  /** 定位说明；仅在 value 不够直观时补充。 */
  description?: string;
}

/** ValidationCatalog 的来源注册项；保留可审计定位信息，不复制来源正文。 */
export interface AssetSourceRef {
  /** 来源引用 run 内 ID；所有 SourcedClaim.source_ref_ids 必须引用当前 catalog 中的 ID。 */
  source_ref_id: string;
  /** 来源类型，例如 BDD、capability、synaptic、issue、spec、PR、commit、artifact 或 CodeGraph symbol。 */
  type: "bdd" | "capability" | "synaptic" | "knowledge" | "spec" | "plan" | "task" | "doc" | "issue" | "project" | "discussion" | "comment" | "pr" | "commit" | "artifact" | "implementation" | "validator" | "codegraph_symbol" | "user_confirmation" | "other";
  /** 当前 run 内该来源的收集方式；生产源码来源必须是 codegraph 或合规 rg-fallback。 */
  collection_method: "codegraph" | "rg-fallback" | "file-read" | "hippocampus-parse" | "synaptic-parse" | "user-confirmation" | "runtime-request" | "other";
  /** 来源系统内的稳定引用，例如 scenario_id、capability_id、feature_id、issue id、commit hash、artifact id 或文档路径。 */
  ref: string;
  /** 本地路径、运行时 URI、知识库 URI 或外部 URL。 */
  uri: string;
  /** 来源内的具体定位，避免只引用粗粒度文档。 */
  locator: SourceLocator;
  /** 来源摘要，说明该来源对当前验证输入的价值。 */
  summary: string;
  /** 外部 URL；适用于 GitHub、Jira、设计文档或外部系统。 */
  url?: string;
  /** CodeGraph 可直接搜索的符号键列表，例如完整限定名、路径归一化符号或方法名。 */
  symbol_refs?: string[];
}

/** ValidationCatalog 的证据注册项；记录 claim 的支撑证据，不替代执行阶段重新采集证据。 */
export interface EvidenceRef {
  /** 证据引用 run 内 ID；所有 SourcedClaim.evidence_ref_ids 必须引用当前 catalog 中的 ID。 */
  evidence_ref_id: string;
  /** 证据类型，例如行为描述、历史验证摘要、缺口、源码审查、artifact、日志、runtime 或用户确认；不表示测试源码。 */
  type: "behavior" | "historical_validation" | "gap" | "source_review" | "artifact" | "log" | "runtime" | "user_confirmation" | "other";
  /** 证据稳定引用，例如验证报告段落、artifact 路径、日志 key、BDD evidence 行或用户确认 ID。 */
  ref: string;
  /** 证据摘要；只描述该证据支持什么，不复制证据正文。 */
  summary: string;
  /** 支撑该证据引用的 SourceRef ID 列表。 */
  source_ref_ids: string[];
}

/** 带来源的最小解释性事实；Fact 中每一句会影响 Planner 的解释都必须表达为 SourcedClaim。 */
export interface SourcedClaim {
  /** claim 稳定 ID。 */
  claim_id: string;
  /** 单句事实陈述；一个 claim 只表达一个事实。 */
  text: string;
  /** 支撑该 claim 的 SourceRef ID 列表；必须至少包含一个可定位来源。 */
  source_ref_ids: string[];
  /** 支撑该 claim 的 EvidenceRef ID 列表；无独立证据时可为空数组，但 source_ref_ids 不能空。 */
  evidence_ref_ids: string[];
  /** 支撑等级；区分直接来源、推断、综合、部分证据、缺失证据和用户确认。 */
  support_level: "direct" | "inferred" | "synthesized" | "partial" | "missing" | "user_confirmed";
  /** 该 claim 对 Planner 的具体用途，例如限定 scope、选择证据通道、建立不足证据条件或识别风险。 */
  planner_use: string;
}
