// Generated by schemas/input/scripts/generate-validation-body.ts from schemas/input/validation-body/*.yaml.
// Do not edit this file by hand.

import type { SourcedClaim } from "./source-ref.generated.js";

/** 当前 BDD 相关的设计承诺投影；只保留会约束 Planner 验证策略的规格信息。 */
export interface SpecificationFact {
  /** specification fact 稳定 ID。 */
  fact_id: string;
  /** 固定为 specification_fact。 */
  fact_type: "specification_fact";
  /** 设计承诺、非目标、边界约束和与当前 BDD 的关系 claim。 */
  claims: SourcedClaim[];
}
