// Generated by schemas/input/scripts/generate-validation-body.ts from schemas/input/validation-body/*.yaml.
// Do not edit this file by hand.

import { readFileSync } from "node:fs";
import { dirname, isAbsolute, resolve } from "node:path";
import type { ValidationBody } from "./body.generated.js";
import type { ValidationCatalog } from "./catalog.generated.js";

type FieldSchema = Readonly<{
  type: string;
  required: boolean;
  description?: string;
}>;

type DeclarationSchema = Readonly<{
  kind: "enum" | "interface" | "inline_object";
  description?: string;
  values?: readonly string[];
  fields?: Readonly<Record<string, FieldSchema>>;
}>;

export const validationBodyRuntimeSchema = {
  "SourceLocator": {
    "kind": "inline_object",
    "fields": {
      "kind": {
        "type": "\"frontmatter\" | \"heading\" | \"line_range\" | \"table_row\" | \"symbol\" | \"json_path\" | \"file\" | \"user_confirmation\" | \"other\"",
        "required": true,
        "description": "来源定位类型，用于把来源具体到字段、段落、表格行、符号、JSON 路径、文件或用户确认。"
      },
      "value": {
        "type": "string",
        "required": true,
        "description": "来源定位值，例如 frontmatter:scenario_id、heading:Given、line_range:31-38、symbol:ConsentManager.RequestAgeSignals。"
      },
      "description": {
        "type": "string",
        "required": false,
        "description": "定位说明；仅在 value 不够直观时补充。"
      }
    }
  },
  "AssetSourceRef": {
    "kind": "interface",
    "description": "ValidationCatalog 的来源注册项；保留可审计定位信息，不复制来源正文。",
    "fields": {
      "source_ref_id": {
        "type": "string",
        "required": true,
        "description": "来源引用 run 内 ID；所有 SourcedClaim.source_ref_ids 必须引用当前 catalog 中的 ID。"
      },
      "type": {
        "type": "\"bdd\" | \"capability\" | \"synaptic\" | \"knowledge\" | \"spec\" | \"plan\" | \"task\" | \"doc\" | \"issue\" | \"project\" | \"discussion\" | \"comment\" | \"pr\" | \"commit\" | \"artifact\" | \"implementation\" | \"validator\" | \"codegraph_symbol\" | \"user_confirmation\" | \"other\"",
        "required": true,
        "description": "来源类型，例如 BDD、capability、synaptic、issue、spec、PR、commit、artifact 或 CodeGraph symbol。"
      },
      "collection_method": {
        "type": "\"codegraph\" | \"rg-fallback\" | \"file-read\" | \"hippocampus-parse\" | \"synaptic-parse\" | \"user-confirmation\" | \"runtime-request\" | \"other\"",
        "required": true,
        "description": "当前 run 内该来源的收集方式；生产源码来源必须是 codegraph 或合规 rg-fallback。"
      },
      "ref": {
        "type": "string",
        "required": true,
        "description": "来源系统内的稳定引用，例如 scenario_id、capability_id、feature_id、issue id、commit hash、artifact id 或文档路径。"
      },
      "uri": {
        "type": "string",
        "required": true,
        "description": "本地路径、运行时 URI、知识库 URI 或外部 URL。"
      },
      "locator": {
        "type": "SourceLocator",
        "required": true,
        "description": "来源内的具体定位，避免只引用粗粒度文档。"
      },
      "summary": {
        "type": "string",
        "required": true,
        "description": "来源摘要，说明该来源对当前验证输入的价值。"
      },
      "url": {
        "type": "string",
        "required": false,
        "description": "外部 URL；适用于 GitHub、Jira、设计文档或外部系统。"
      },
      "symbol_refs": {
        "type": "string[]",
        "required": false,
        "description": "CodeGraph 可直接搜索的符号键列表，例如完整限定名、路径归一化符号或方法名。"
      }
    }
  },
  "EvidenceRef": {
    "kind": "interface",
    "description": "ValidationCatalog 的证据注册项；记录 claim 的支撑证据，不替代执行阶段重新采集证据。",
    "fields": {
      "evidence_ref_id": {
        "type": "string",
        "required": true,
        "description": "证据引用 run 内 ID；所有 SourcedClaim.evidence_ref_ids 必须引用当前 catalog 中的 ID。"
      },
      "type": {
        "type": "\"behavior\" | \"historical_validation\" | \"gap\" | \"source_review\" | \"artifact\" | \"log\" | \"runtime\" | \"user_confirmation\" | \"other\"",
        "required": true,
        "description": "证据类型，例如行为描述、历史验证摘要、缺口、源码审查、artifact、日志、runtime 或用户确认；不表示测试源码。"
      },
      "ref": {
        "type": "string",
        "required": true,
        "description": "证据稳定引用，例如验证报告段落、artifact 路径、日志 key、BDD evidence 行或用户确认 ID。"
      },
      "summary": {
        "type": "string",
        "required": true,
        "description": "证据摘要；只描述该证据支持什么，不复制证据正文。"
      },
      "source_ref_ids": {
        "type": "string[]",
        "required": true,
        "description": "支撑该证据引用的 SourceRef ID 列表。"
      }
    }
  },
  "SourcedClaim": {
    "kind": "interface",
    "description": "带来源的最小解释性事实；Fact 中每一句会影响 Planner 的解释都必须表达为 SourcedClaim。",
    "fields": {
      "claim_id": {
        "type": "string",
        "required": true,
        "description": "claim 稳定 ID。"
      },
      "text": {
        "type": "string",
        "required": true,
        "description": "单句事实陈述；一个 claim 只表达一个事实。"
      },
      "source_ref_ids": {
        "type": "string[]",
        "required": true,
        "description": "支撑该 claim 的 SourceRef ID 列表；必须至少包含一个可定位来源。"
      },
      "evidence_ref_ids": {
        "type": "string[]",
        "required": true,
        "description": "支撑该 claim 的 EvidenceRef ID 列表；无独立证据时可为空数组，但 source_ref_ids 不能空。"
      },
      "support_level": {
        "type": "\"direct\" | \"inferred\" | \"synthesized\" | \"partial\" | \"missing\" | \"user_confirmed\"",
        "required": true,
        "description": "支撑等级；区分直接来源、推断、综合、部分证据、缺失证据和用户确认。"
      },
      "planner_use": {
        "type": "string",
        "required": true,
        "description": "该 claim 对 Planner 的具体用途，例如限定 scope、选择证据通道、建立不足证据条件或识别风险。"
      }
    }
  },
  "ImplementationRef": {
    "kind": "interface",
    "description": "ValidationCatalog 的实现定位注册项；只记录生产源码、配置、符号或 artifact 的可定位引用，不承载 Planner 语义。",
    "fields": {
      "implementation_ref_id": {
        "type": "string",
        "required": true,
        "description": "实现定位 run 内 ID；用于把 implementation fact 中的生产实现 claim 追溯到可定位源码或 artifact。"
      },
      "kind": {
        "type": "\"module\" | \"source_path\" | \"config\" | \"api\" | \"event\" | \"callback\" | \"schema\" | \"asset\" | \"symbol\"",
        "required": true,
        "description": "定位类型，例如模块、源码路径、配置、API、事件、callback、schema、asset 或符号。"
      },
      "ref": {
        "type": "string",
        "required": true,
        "description": "实现定位引用，例如模块名、源码路径、API 名称、事件名、symbol 或 asset path。"
      },
      "uri": {
        "type": "string",
        "required": false,
        "description": "可选本地路径、运行时 URI、知识库 URI 或外部 URL；当 ref 不足以定位时必须提供。"
      },
      "locator": {
        "type": "SourceLocator",
        "required": false,
        "description": "可选来源内具体定位，例如 symbol、line_range、json_path 或 file。"
      },
      "source_ref_ids": {
        "type": "string[]",
        "required": true,
        "description": "支撑该实现定位的 SourceRef ID 列表。"
      }
    }
  },
  "ValidationCatalog": {
    "kind": "interface",
    "description": "ValidationBody 的 run 内来源与证据目录；承载 SourceRef/EvidenceRef 注册表，不承载 Planner 事实。",
    "fields": {
      "catalog_id": {
        "type": "string",
        "required": true,
        "description": "本次 run 内部 catalog ID；只要求在当前 run 内稳定，不作为跨 run 身份。"
      },
      "catalogType": {
        "type": "\"validation_catalog\"",
        "required": true,
        "description": "固定类型标识，表示这是 ValidationBody 配套的引用目录。"
      },
      "runId": {
        "type": "string",
        "required": true,
        "description": "生成该 catalog 的 run ID。"
      },
      "createdAt": {
        "type": "string",
        "required": true,
        "description": "该 catalog 创建时间。"
      },
      "source_refs": {
        "type": "AssetSourceRef[]",
        "required": true,
        "description": "本 catalog 的来源注册表；所有 claim 必须引用这里的 source_ref_id。"
      },
      "evidence_refs": {
        "type": "EvidenceRef[]",
        "required": true,
        "description": "本 catalog 的证据注册表；历史证据只作为计划输入，不替代当前 run 证据。"
      },
      "implementation_refs": {
        "type": "ImplementationRef[]",
        "required": true,
        "description": "本 catalog 的实现定位注册表；只记录定位，不记录 Planner 决策语义。"
      }
    }
  },
  "BddFact": {
    "kind": "interface",
    "description": "当前验证的 BDD 事实投影；只承载 BDD identity、Given/When/Then 与对 Planner 有用的场景约束。",
    "fields": {
      "fact_id": {
        "type": "string",
        "required": true,
        "description": "BDD fact 稳定 ID。"
      },
      "fact_type": {
        "type": "\"bdd_fact\"",
        "required": true,
        "description": "固定为 bdd_fact。"
      },
      "scenario_id": {
        "type": "string",
        "required": true,
        "description": "BDD 场景稳定 ID。"
      },
      "claims": {
        "type": "SourcedClaim[]",
        "required": false,
        "description": "除 Given / When / Then 之外仍会影响 Planner 的 BDD 场景 claim；没有明确来源或用途时不要填写。"
      },
      "given": {
        "type": "SourcedClaim[]",
        "required": true,
        "description": "BDD Given 语义；每个步骤都必须是带来源 claim。"
      },
      "when": {
        "type": "SourcedClaim[]",
        "required": true,
        "description": "BDD When 语义；每个步骤都必须是带来源 claim。"
      },
      "then": {
        "type": "SourcedClaim[]",
        "required": true,
        "description": "BDD Then 语义；每个步骤都必须是带来源 claim。"
      }
    }
  },
  "CapabilityFact": {
    "kind": "interface",
    "description": "当前 BDD 条件下的 capability 摘要投影；只保留对 Plan 有用的信息，不复刻 hippocampus capability 对象。",
    "fields": {
      "fact_id": {
        "type": "string",
        "required": true,
        "description": "capability fact 稳定 ID，建议包含 BDD scenario 与来源 capability。"
      },
      "fact_type": {
        "type": "\"capability_fact\"",
        "required": true,
        "description": "固定为 capability_fact。"
      },
      "relevant_bdd_refs": {
        "type": "string[]",
        "required": true,
        "description": "该 capability fact 直接服务的 BDD 场景 ID。"
      },
      "claims": {
        "type": "SourcedClaim[]",
        "required": true,
        "description": "对当前 BDD 有用的 capability 事实；每一句都必须可追溯到具体来源。"
      },
      "excluded_context": {
        "type": "SourcedClaim[]",
        "required": false,
        "description": "已遍历但不进入 Planner 主上下文的 capability/synaptic/knowledge 信息及排除原因。"
      }
    }
  },
  "RequirementFact": {
    "kind": "interface",
    "description": "当前 BDD 相关的需求、规格或 feature 意图投影；只保留 Planner 判断验证目标和验收口径所需的信息。",
    "fields": {
      "fact_id": {
        "type": "string",
        "required": true,
        "description": "requirement fact 稳定 ID。"
      },
      "fact_type": {
        "type": "\"requirement_fact\"",
        "required": true,
        "description": "固定为 requirement_fact。"
      },
      "claims": {
        "type": "SourcedClaim[]",
        "required": true,
        "description": "需求意图、验收口径、当前 BDD 覆盖范围和不覆盖范围的 claim。"
      }
    }
  },
  "SpecificationFact": {
    "kind": "interface",
    "description": "当前 BDD 相关的设计承诺投影；只保留会约束 Planner 验证策略的规格信息。",
    "fields": {
      "fact_id": {
        "type": "string",
        "required": true,
        "description": "specification fact 稳定 ID。"
      },
      "fact_type": {
        "type": "\"specification_fact\"",
        "required": true,
        "description": "固定为 specification_fact。"
      },
      "claims": {
        "type": "SourcedClaim[]",
        "required": true,
        "description": "设计承诺、非目标、边界约束和与当前 BDD 的关系 claim。"
      }
    }
  },
  "FeatureFact": {
    "kind": "interface",
    "description": "当前 BDD 相关的 synaptic proposal 事实投影；只保留 proposal 中会影响 Planner 的需求背景、目标、范围和非目标。",
    "fields": {
      "fact_id": {
        "type": "string",
        "required": true,
        "description": "feature fact 稳定 ID。"
      },
      "fact_type": {
        "type": "\"feature_fact\"",
        "required": true,
        "description": "固定为 feature_fact。"
      },
      "claims": {
        "type": "SourcedClaim[]",
        "required": true,
        "description": "proposal 的动机、目标、范围、非目标、用户价值和与当前 BDD 的关系 claim。"
      }
    }
  },
  "ImplementationFact": {
    "kind": "interface",
    "description": "当前 BDD 相关的生产实现覆盖投影；只记录已通过 CodeGraph 或合规 rg 回退校验的生产源码、配置、API、symbol 或 artifact 事实。",
    "fields": {
      "fact_id": {
        "type": "string",
        "required": true,
        "description": "implementation fact 稳定 ID。"
      },
      "fact_type": {
        "type": "\"implementation_fact\"",
        "required": true,
        "description": "固定为 implementation_fact。"
      },
      "coverage_status": {
        "type": "\"covered\" | \"partial\" | \"missing\" | \"out_of_scope\"",
        "required": true,
        "description": "当前 BDD 对应实现覆盖状态；必须由 claim 与 evidence 支撑。"
      },
      "claims": {
        "type": "SourcedClaim[]",
        "required": true,
        "description": "生产实现覆盖、源码/API/配置/artifact、历史 gap 与当前验证影响的 claim；不得纳入测试代码。"
      }
    }
  },
  "ValidationCatalogRef": {
    "kind": "inline_object",
    "fields": {
      "catalog_id": {
        "type": "string",
        "required": true,
        "description": "与本 ValidationBody 配套的 catalog ID；只要求在当前 run 内稳定。"
      },
      "uri": {
        "type": "string",
        "required": true,
        "description": "catalog JSON 的本地路径、运行时 URI 或相对路径。"
      },
      "digest": {
        "type": "string",
        "required": false,
        "description": "可选内容摘要；用于需要时校验 catalog 未漂移。"
      }
    }
  },
  "AcceptanceCriteria": {
    "kind": "inline_object",
    "description": "当前 BDD 的验收口径；只写有证据、有意义、会影响 Planner 判断的条件。",
    "fields": {
      "pass_conditions": {
        "type": "SourcedClaim[]",
        "required": false,
        "description": "满足哪些明确条件才算验证通过；没有明确依据时不要填写。"
      },
      "fail_conditions": {
        "type": "SourcedClaim[]",
        "required": false,
        "description": "出现哪些明确条件应判定为失败；没有明确依据时不要填写。"
      },
      "insufficient_evidence_conditions": {
        "type": "SourcedClaim[]",
        "required": false,
        "description": "哪些情况下不能判定通过；只记录已确认的证据不足条件。"
      }
    }
  },
  "ValidationBody": {
    "kind": "interface",
    "fields": {
      "validationBodyId": {
        "type": "string",
        "required": true,
        "description": "本次 run 内部 Validation Body ID；用于 run 内追踪和历史归类，不作为跨 run 业务身份。"
      },
      "bodyType": {
        "type": "\"validation_body\"",
        "required": true,
        "description": "固定类型标识，表示这是 Scout 内部的 Validation Body。"
      },
      "runId": {
        "type": "string",
        "required": true,
        "description": "生成该 ValidationBody 的 run ID。"
      },
      "createdAt": {
        "type": "string",
        "required": true,
        "description": "该 ValidationBody 创建时间。"
      },
      "catalog_ref": {
        "type": "ValidationCatalogRef",
        "required": true,
        "description": "本 ValidationBody 配套的 run 内引用目录；所有 source_ref_ids 和 evidence_ref_ids 都必须在该 catalog 中解析。"
      },
      "bdd_fact": {
        "type": "BddFact",
        "required": true,
        "description": "BDD 事实；承载当前 BDD 的 Given / When / Then 和场景身份。"
      },
      "requirement_facts": {
        "type": "RequirementFact[]",
        "required": false,
        "description": "当前 BDD 相关的需求意图和验收口径；只保留会影响 Planner 的 claim。"
      },
      "specification_facts": {
        "type": "SpecificationFact[]",
        "required": false,
        "description": "当前 BDD 相关的设计承诺和规格约束；只保留会影响 Planner 的 claim。"
      },
      "feature_facts": {
        "type": "FeatureFact[]",
        "required": false,
        "description": "当前 BDD 相关的 synaptic proposal 事实；只保留 proposal 中会影响 Planner 的 claim。"
      },
      "implementation_facts": {
        "type": "ImplementationFact[]",
        "required": false,
        "description": "当前 BDD 相关的生产实现覆盖；只保留经过源码真实性校验的 claim。"
      },
      "capability_facts": {
        "type": "CapabilityFact[]",
        "required": false,
        "description": "当前 BDD 条件下的 capability 摘要投影；只保留对 Plan 有用的信息。"
      },
      "acceptance_criteria": {
        "type": "AcceptanceCriteria",
        "required": false,
        "description": "本次验证的通过、失败和证据不足条件；不要为了填满字段编造。"
      },
      "given": {
        "type": "string[]",
        "required": true,
        "description": "从 bdd_fact.given[].text 投影出的 Given 文本，供 Planner 快速读取。"
      },
      "when": {
        "type": "string[]",
        "required": true,
        "description": "从 bdd_fact.when[].text 投影出的 When 文本，供 Planner 快速读取。"
      },
      "then": {
        "type": "string[]",
        "required": true,
        "description": "从 bdd_fact.then[].text 投影出的 Then 文本，供 Planner 快速读取。"
      },
      "constraints": {
        "type": "SourcedClaim[]",
        "required": false,
        "description": "输入材料中明确限制执行、判断、资源、环境或安全边界的约束。"
      },
      "uncertainty_items": {
        "type": "SourcedClaim[]",
        "required": false,
        "description": "输入中缺失、矛盾、不可观测或需要人工处理的不确定项。"
      }
    }
  }
} as const satisfies Readonly<Record<string, DeclarationSchema>>;

const schema: Readonly<Record<string, DeclarationSchema>> = validationBodyRuntimeSchema;
const validationBodyCompletenessPaths = [
  "catalog_ref.uri",
  "bdd_fact.scenario_id",
  "given",
  "when",
  "then"
] as const;

export function createValidationBodySkeleton(input: {
  validationBodyId: string;
  runId: string;
  createdAt: string;
}): ValidationBody {
  const skeleton = createSkeletonForDeclaration("ValidationBody") as Record<string, unknown>;
  skeleton.validationBodyId = input.validationBodyId;
  skeleton.runId = input.runId;
  skeleton.createdAt = input.createdAt;
  return skeleton as unknown as ValidationBody;
}

export function validateValidationCatalog(value: unknown): string[] {
  const errors: string[] = [];
  validateType(value, "ValidationCatalog", "validationCatalog", errors);
  if (errors.length === 0) {
    validateSemanticConstraints(value, "validationCatalog", errors);
    validateCatalogRefs(value, errors);
  }
  return errors;
}

export function validateValidationBody(value: unknown, catalog?: unknown): string[] {
  const errors: string[] = [];
  validateType(value, "ValidationBody", "validationBody", errors);
  if (errors.length === 0) {
    validateSemanticConstraints(value, "validationBody", errors);
    if (catalog === undefined) {
      errors.push("validationBody.catalog_ref requires a ValidationCatalog for semantic validation.");
    } else {
      validateType(catalog, "ValidationCatalog", "validationCatalog", errors);
      if (errors.length === 0) {
        validateSemanticConstraints(catalog, "validationCatalog", errors);
        validateCatalogRefs(catalog, errors);
        validateValidationBodySemanticRelations(value, catalog, errors);
      }
    }
  }
  if (errors.length === 0 && !validationBodyComplete(value as ValidationBody)) {
    errors.push("validationBody is structurally valid but incomplete for plan build.");
  }
  return errors;
}

export function validationBodyComplete(validationBody: ValidationBody): boolean {
  return validationBodyCompletenessPaths.every((path) => hasNonEmptyValue(readPath(validationBody, path)));
}

function createSkeletonForDeclaration(name: string): unknown {
  const declaration = schema[name];
  if (!declaration) {
    throw new Error(`Unknown validation body declaration: ${name}`);
  }
  if (declaration.kind === "enum") {
    return declaration.values?.[0] ?? "";
  }

  const result: Record<string, unknown> = {};
  for (const [fieldName, field] of Object.entries(declaration.fields ?? {})) {
    if (field.required) {
      result[fieldName] = createSkeletonForType(field.type);
    }
  }
  return result;
}

function createSkeletonForType(type: string): unknown {
  const arrayElementType = readArrayElementType(type);
  if (arrayElementType) return [];

  const literalOptions = readLiteralOptions(type);
  if (literalOptions.length > 0) return literalOptions[0];

  if (type === "string") return "";
  if (type === "number") return 0;
  if (type === "boolean") return false;
  if (schema[type]) return createSkeletonForDeclaration(type);

  throw new Error(`Unsupported validation body skeleton type: ${type}`);
}

function validateType(value: unknown, type: string, path: string, errors: string[]): void {
  const arrayElementType = readArrayElementType(type);
  if (arrayElementType) {
    if (!Array.isArray(value)) {
      errors.push(`${path} must be an array.`);
      return;
    }
    for (const [index, item] of value.entries()) {
      validateType(item, arrayElementType, `${path}[${index}]`, errors);
    }
    return;
  }

  const literalOptions = readLiteralOptions(type);
  if (literalOptions.length > 0) {
    if (!literalOptions.includes(value as string | number | boolean)) {
      errors.push(`${path} must be ${formatOptions(literalOptions)}.`);
    }
    return;
  }

  if (type === "string") {
    if (typeof value !== "string" || value.length === 0) {
      errors.push(`${path} must be a non-empty string.`);
    }
    return;
  }

  if (type === "number") {
    if (typeof value !== "number" || !Number.isFinite(value)) {
      errors.push(`${path} must be a finite number.`);
    }
    return;
  }

  if (type === "boolean") {
    if (typeof value !== "boolean") {
      errors.push(`${path} must be a boolean.`);
    }
    return;
  }

  const declaration = schema[type];
  if (!declaration) {
    errors.push(`${path} uses unknown validation body schema type ${type}.`);
    return;
  }

  if (declaration.kind === "enum") {
    if (typeof value !== "string" || !(declaration.values ?? []).includes(value)) {
      errors.push(`${path} must be one of ${formatOptions(declaration.values ?? [])}.`);
    }
    return;
  }

  if (!isRecord(value)) {
    errors.push(`${path} must be an object.`);
    return;
  }

  for (const [fieldName, field] of Object.entries(declaration.fields ?? {})) {
    const fieldPath = `${path}.${fieldName}`;
    if (!(fieldName in value)) {
      if (field.required) {
        errors.push(`${fieldPath} is required.`);
      }
      continue;
    }
    const fieldValue = value[fieldName];
    if (fieldValue === undefined) {
      if (field.required) {
        errors.push(`${fieldPath} is required.`);
      }
      continue;
    }
    validateType(fieldValue, field.type, fieldPath, errors);
  }
}

function validateSemanticConstraints(value: unknown, path: string, errors: string[]): void {
  if (Array.isArray(value)) {
    for (const [index, item] of value.entries()) {
      validateSemanticConstraints(item, `${path}[${index}]`, errors);
    }
    return;
  }

  if (!isRecord(value)) return;

  if (value.type === "codegraph_symbol") {
    const symbolRefs = value.symbol_refs;
    if (!Array.isArray(symbolRefs) || symbolRefs.length === 0) {
      errors.push(`${path}.symbol_refs must be a non-empty array when type is codegraph_symbol.`);
    }
  }

  for (const [fieldName, fieldValue] of Object.entries(value)) {
    validateSemanticConstraints(fieldValue, `${path}.${fieldName}`, errors);
  }
}

function validateValidationBodySemanticRelations(value: unknown, catalog: unknown, errors: string[]): void {
  if (!isRecord(value)) return;
  validateBddProjection(value, "given", errors);
  validateBddProjection(value, "when", errors);
  validateBddProjection(value, "then", errors);
  validateCatalogRefMatches(value, catalog, errors);
  validateSourcedClaimRefs(value, catalog, errors);
}

function validateBddProjection(
  validationBody: Record<string, unknown>,
  key: "given" | "when" | "then",
  errors: string[],
): void {
  const topLevel = validationBody[key];
  const bddFact = validationBody.bdd_fact;
  if (!Array.isArray(topLevel) || !isRecord(bddFact) || !Array.isArray(bddFact[key])) return;

  const bddSteps = bddFact[key]
    .map((item) => isRecord(item) && typeof item.text === "string" ? item.text.trim() : "")
    .filter((item) => item.length > 0);
  const topLevelSteps = topLevel
    .map((item) => typeof item === "string" ? item.trim() : "")
    .filter((item) => item.length > 0);
  if (bddSteps.length === 0 || topLevelSteps.length === 0) return;
  if (JSON.stringify(bddSteps) !== JSON.stringify(topLevelSteps)) {
    errors.push(`validationBody.${key} must match validationBody.bdd_fact.${key}[].text.`);
  }
}

function validateCatalogRefMatches(validationBody: Record<string, unknown>, catalog: unknown, errors: string[]): void {
  const catalogRef = validationBody.catalog_ref;
  if (!isRecord(catalogRef) || !isRecord(catalog)) return;
  if (catalogRef.catalog_id !== catalog.catalog_id) {
    errors.push(`validationBody.catalog_ref.catalog_id must match validationCatalog.catalog_id.`);
  }
}

function validateCatalogRefs(catalog: unknown, errors: string[]): void {
  if (!isRecord(catalog)) return;
  const sourceRefs = catalog.source_refs;
  const evidenceRefs = catalog.evidence_refs;
  const implementationRefs = catalog.implementation_refs;
  const sourceRefIds = new Set<string>();
  const evidenceRefIds = new Set<string>();
  const implementationRefIds = new Set<string>();

  if (Array.isArray(sourceRefs)) {
    for (const [index, item] of sourceRefs.entries()) {
      if (!isRecord(item)) continue;
      const id = item.source_ref_id;
      if (typeof id !== "string" || id.trim().length === 0) continue;
      if (sourceRefIds.has(id)) {
        errors.push(`validationCatalog.source_refs[${index}].source_ref_id duplicates ${id}.`);
      }
      sourceRefIds.add(id);
    }
  }

  if (Array.isArray(evidenceRefs)) {
    for (const [index, item] of evidenceRefs.entries()) {
      if (!isRecord(item)) continue;
      const id = item.evidence_ref_id;
      if (typeof id !== "string" || id.trim().length === 0) continue;
      if (evidenceRefIds.has(id)) {
        errors.push(`validationCatalog.evidence_refs[${index}].evidence_ref_id duplicates ${id}.`);
      }
      evidenceRefIds.add(id);

      const sourceIds = item.source_ref_ids;
      if (Array.isArray(sourceIds)) {
        for (const sourceId of sourceIds) {
          if (typeof sourceId === "string" && !sourceRefIds.has(sourceId)) {
            errors.push(`validationCatalog.evidence_refs[${index}].source_ref_ids references unknown source_ref_id ${sourceId}.`);
          }
        }
      }
    }
  }

  if (Array.isArray(implementationRefs)) {
    for (const [index, item] of implementationRefs.entries()) {
      if (!isRecord(item)) continue;
      const id = item.implementation_ref_id;
      if (typeof id !== "string" || id.trim().length === 0) continue;
      if (implementationRefIds.has(id)) {
        errors.push(`validationCatalog.implementation_refs[${index}].implementation_ref_id duplicates ${id}.`);
      }
      implementationRefIds.add(id);

      const sourceIds = item.source_ref_ids;
      if (Array.isArray(sourceIds)) {
        for (const sourceId of sourceIds) {
          if (typeof sourceId === "string" && !sourceRefIds.has(sourceId)) {
            errors.push(`validationCatalog.implementation_refs[${index}].source_ref_ids references unknown source_ref_id ${sourceId}.`);
          }
        }
      }
    }
  }
}

function validateSourcedClaimRefs(validationBody: Record<string, unknown>, catalog: unknown, errors: string[]): void {
  if (!isRecord(catalog)) return;
  const sourceRefs = catalog.source_refs;
  const evidenceRefs = catalog.evidence_refs;
  const sourceRefIds = new Set<string>();
  const evidenceRefIds = new Set<string>();

  if (Array.isArray(sourceRefs)) {
    for (const item of sourceRefs) {
      if (!isRecord(item)) continue;
      const id = item.source_ref_id;
      if (typeof id === "string" && id.trim().length > 0) sourceRefIds.add(id);
    }
  }
  if (Array.isArray(evidenceRefs)) {
    for (const item of evidenceRefs) {
      if (!isRecord(item)) continue;
      const id = item.evidence_ref_id;
      if (typeof id === "string" && id.trim().length > 0) evidenceRefIds.add(id);
    }
  }
  validateClaimsInValue(validationBody, "validationBody", sourceRefIds, evidenceRefIds, errors);
  validateImplementationRefsInValue(validationBody, "validationBody", catalog, errors);
}

function validateImplementationRefsInValue(
  value: unknown,
  path: string,
  catalog: unknown,
  errors: string[],
): void {
  const implementationRefIds = collectImplementationRefIds(catalog);
  validateImplementationRefsAgainstSet(value, path, implementationRefIds, errors);
}

function collectImplementationRefIds(catalog: unknown): Set<string> {
  const ids = new Set<string>();
  if (!isRecord(catalog) || !Array.isArray(catalog.implementation_refs)) return ids;
  for (const item of catalog.implementation_refs) {
    if (!isRecord(item)) continue;
    const id = item.implementation_ref_id;
    if (typeof id === "string" && id.trim().length > 0) ids.add(id);
  }
  return ids;
}

function validateImplementationRefsAgainstSet(
  value: unknown,
  path: string,
  implementationRefIds: Set<string>,
  errors: string[],
): void {
  if (Array.isArray(value)) {
    for (const [index, item] of value.entries()) {
      validateImplementationRefsAgainstSet(item, `${path}[${index}]`, implementationRefIds, errors);
    }
    return;
  }
  if (!isRecord(value)) return;

  if (Array.isArray(value.implementation_ref_ids)) {
    if (value.implementation_ref_ids.length === 0) {
      errors.push(`${path}.implementation_ref_ids must contain at least one implementation_ref_id.`);
    }
    for (const implementationRefId of value.implementation_ref_ids) {
      if (typeof implementationRefId === "string" && !implementationRefIds.has(implementationRefId)) {
        errors.push(`${path}.implementation_ref_ids references unknown implementation_ref_id ${implementationRefId}.`);
      }
    }
  }

  for (const [fieldName, fieldValue] of Object.entries(value)) {
    validateImplementationRefsAgainstSet(fieldValue, `${path}.${fieldName}`, implementationRefIds, errors);
  }
}

function validateClaimsInValue(
  value: unknown,
  path: string,
  sourceRefIds: Set<string>,
  evidenceRefIds: Set<string>,
  errors: string[],
): void {
  if (Array.isArray(value)) {
    for (const [index, item] of value.entries()) {
      validateClaimsInValue(item, `${path}[${index}]`, sourceRefIds, evidenceRefIds, errors);
    }
    return;
  }

  if (!isRecord(value)) return;

  if (typeof value.claim_id === "string" && typeof value.text === "string") {
    const sourceIds = value.source_ref_ids;
    if (!Array.isArray(sourceIds) || sourceIds.length === 0) {
      errors.push(`${path}.source_ref_ids must contain at least one source_ref_id.`);
    } else {
      for (const sourceId of sourceIds) {
        if (typeof sourceId === "string" && !sourceRefIds.has(sourceId)) {
          errors.push(`${path}.source_ref_ids references unknown source_ref_id ${sourceId}.`);
        }
      }
    }

    const evidenceIds = value.evidence_ref_ids;
    if (Array.isArray(evidenceIds)) {
      for (const evidenceId of evidenceIds) {
        if (typeof evidenceId === "string" && !evidenceRefIds.has(evidenceId)) {
          errors.push(`${path}.evidence_ref_ids references unknown evidence_ref_id ${evidenceId}.`);
        }
      }
    }
  }

  for (const [fieldName, fieldValue] of Object.entries(value)) {
    validateClaimsInValue(fieldValue, `${path}.${fieldName}`, sourceRefIds, evidenceRefIds, errors);
  }
}

function readArrayElementType(type: string): string | undefined {
  return type.endsWith("[]") ? type.slice(0, -2) : undefined;
}

function readLiteralOptions(type: string): Array<string | number | boolean> {
  const parts = type.split("|").map((part) => part.trim());
  const literals = parts.map(readLiteralOption);
  return literals.every((literal) => literal !== undefined)
    ? literals as Array<string | number | boolean>
    : [];
}

function readLiteralOption(type: string): string | number | boolean | undefined {
  if ((type.startsWith('"') && type.endsWith('"')) || (type.startsWith("'") && type.endsWith("'"))) {
    return type.slice(1, -1);
  }
  if (/^-?\d+(?:\.\d+)?$/.test(type)) {
    return Number(type);
  }
  if (type === "true") return true;
  if (type === "false") return false;
  return undefined;
}

function formatOptions(values: readonly unknown[]): string {
  return values.map((value) => JSON.stringify(value)).join(" | ");
}

function readPath(value: unknown, path: string): unknown {
  let current = value;
  for (const segment of path.split(".")) {
    if (!isRecord(current)) return undefined;
    current = current[segment];
  }
  return current;
}

function hasNonEmptyValue(value: unknown): boolean {
  if (typeof value === "string") return value.trim().length > 0;
  if (Array.isArray(value)) return value.length > 0;
  if (isRecord(value)) return Object.keys(value).length > 0;
  return value !== undefined && value !== null;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function runCli(): void {
  const filePath = process.argv[2];
  if (!filePath) {
    process.stderr.write("Usage: validation <scout-input.json | validation-body.json>\n");
    process.exitCode = 1;
    return;
  }

  const parsed = JSON.parse(readFileSync(filePath, "utf8")) as unknown;
  const subject = isRecord(parsed) && "validationBody" in parsed ? parsed.validationBody : parsed;
  const catalog = readCatalogForSubject(parsed, subject, filePath);
  const errors = validateValidationBody(subject, catalog);
  if (errors.length > 0) {
    process.stderr.write(errors.join("\n") + "\n");
    process.exitCode = 1;
    return;
  }

  process.stdout.write(JSON.stringify({ status: "passed", filePath }, null, 2) + "\n");
}

function readCatalogForSubject(parsed: unknown, subject: unknown, filePath: string): unknown {
  if (isRecord(parsed) && "validationCatalog" in parsed) return parsed.validationCatalog;
  if (!isRecord(subject) || !isRecord(subject.catalog_ref)) return undefined;
  const uri = subject.catalog_ref.uri;
  if (typeof uri !== "string" || uri.trim().length === 0) return undefined;
  const catalogPath = isAbsolute(uri) ? uri : resolve(dirname(filePath), uri);
  return JSON.parse(readFileSync(catalogPath, "utf8")) as unknown;
}

if (process.argv[1]?.endsWith("validation.generated.js")) {
  runCli();
}
