// Generated by schemas/domain/validation/generate-domain-validation.ts from schemas/domain/validation/*.yaml.
// Do not edit this file by hand.


export type ValidationAgentRole =
  | "coordinator"
  | "researcher"
  | "verifier"
  | "validator"
;

export type ValidationTaskStatus =
  | "complete"
  | "prompt_required"
  | "confirmation_required"
  | "blocked"
  | "insufficient_evidence"
  | "failed"
;

export type ValidationArtifactType =
  | "ResearchArtifact"
  | "VerificationReport"
  | "ValidationResult"
  | "ValidationStateSnapshot"
;

/** 可审计定位信息；用于把来源、证据或 artifact 定位到稳定对象。 */
export interface ValidationLocator {
  /** 定位类型。 */
  kind: "file" | "line_range" | "heading" | "json_path" | "symbol" | "command" | "artifact" | "user_confirmation" | "other";
  /** 定位值，例如相对路径、json path、symbol、命令或用户确认 ID。 */
  value: string;
  /** 定位说明。 */
  description?: string;
}

/** 领域 artifact 引用；Coordinator 只通过 refs 观察业务产物。 */
export interface ArtifactRef {
  /** run 内 artifact 引用 ID。 */
  artifact_ref_id: string;
  /** artifact 类型。 */
  artifact_type: ValidationArtifactType;
  /** artifact 路径、运行时 URI 或相对路径。 */
  uri: string;
  /** 产出该 artifact 的 agent role。 */
  agent_role: ValidationAgentRole;
  /** 产出该 artifact 的 task id。 */
  task_id: string;
  /** 产出时间。 */
  produced_at: string;
  /** 可选内容摘要，用于重放时检测漂移。 */
  digest?: string;
}

/** 领域来源引用；保留可审计来源，不复制来源全文。 */
export interface SourceRef {
  /** run 内来源 ID。 */
  source_ref_id: string;
  /** 来源类型。 */
  type: "bdd" | "knowledge" | "codebase" | "source" | "artifact" | "tool_output" | "user_confirmation" | "runtime" | "other";
  /** 本 run 内来源收集方式。 */
  collection_method: "file-read" | "knowledge-read" | "jarvis-codebase" | "codegraph" | "rg-fallback" | "tool-call" | "user-confirmation" | "runtime-event" | "other";
  /** 来源系统内稳定引用，例如 scenario_id、知识库文件、repo 名或 task id。 */
  ref: string;
  /** 来源 URI、路径或本地相对路径。 */
  uri: string;
  /** 来源内定位。 */
  locator: ValidationLocator;
  /** 来源摘要。 */
  summary: string;
}

/** Runtime 观察到的活动引用；只能作为 evidence candidate。 */
export interface ActivityRef {
  /** run 内 activity ID。 */
  activity_ref_id: string;
  /** 活动类型。 */
  type: "tool_call" | "command" | "file_read" | "file_write" | "mcp" | "plan" | "progress" | "runtime_event" | "other";
  /** 工具名、命令、runtime event id 或日志 ref。 */
  ref: string;
  /** 该活动说明发生了什么。 */
  summary: string;
  /** Runtime 观察时间。 */
  observed_at: string;
}

/** 可支撑 Validation State 的证据引用；必须能追溯来源或活动。 */
export interface EvidenceRef {
  /** run 内 evidence ID。 */
  evidence_ref_id: string;
  /** 证据类型。 */
  type: "bdd" | "knowledge" | "code" | "config" | "log" | "artifact" | "tool_output" | "user_confirmation" | "gap" | "other";
  /** 证据稳定引用。 */
  ref: string;
  /** 证据摘要。 */
  summary: string;
  /** 证据内定位。 */
  locator?: ValidationLocator;
  /** 支撑该证据的 SourceRef IDs。 */
  source_ref_ids: string[];
  /** 该证据来自哪些 Runtime activity；activity 不能单独替代证据解释。 */
  activity_ref_ids?: string[];
}

/** 重放上下文；用于复现同一 BDD 在同一知识库、代码库和 asset commit 下的判断。 */
export interface ReplayContext {
  /** 当前 run id。 */
  run_id: string;
  /** 当前 agent mount 的 asset commit id。 */
  asset_commit_id: string;
  /** agent profile 或 role。 */
  agent_profile: string;
  /** 本次使用的知识库根。 */
  knowledge_roots: string[];
  /** 本次涉及的 codebase repo/version/branch 摘要。 */
  codebase_refs: string[];
  /** 影响领域结论的关键命令。 */
  commands: string[];
}
