// Generated by schemas/domain/validation/generate-domain-validation.ts from schemas/domain/validation/*.yaml.
// Do not edit this file by hand.

import type { ActivityRef, EvidenceRef, ReplayContext, SourceRef } from "./common.generated.js";

/** BDD Given / When / Then 的单条语义。 */
export interface BddStatement {
  /** BDD 语句文本。 */
  text: string;
  /** 支撑该语句的来源。 */
  source_ref_ids: string[];
}

/** Researcher 清理后的 BDD 输入。 */
export interface BddFacts {
  /** BDD 场景 ID；无法唯一识别时不能 complete。 */
  scenario_id: string;
  /** 场景标题。 */
  title?: string;
  /** Given 语句。 */
  given: BddStatement[];
  /** When 语句。 */
  when: BddStatement[];
  /** Then 语句。 */
  then: BddStatement[];
  /** 额外验收条件。 */
  acceptance_criteria?: BddStatement[];
}

/** Verifier 后续可使用的实现定位线索；不是最终代码证据。 */
export interface ImplementationHint {
  /** hint ID。 */
  hint_id: string;
  /** 线索类型。 */
  kind: "repo" | "path" | "symbol" | "config" | "log" | "artifact" | "other";
  /** repo、路径、symbol、配置 key 或 artifact ref。 */
  ref: string;
  /** 为什么该线索可能有助于验证。 */
  summary: string;
  /** 线索来源。 */
  source_ref_ids: string[];
}

/** 当前研究阶段无法闭环的不确定项。 */
export interface UncertaintyItem {
  /** 不确定项 ID。 */
  item_id: string;
  /** 对后续验证的影响等级。 */
  severity: "info" | "warning" | "blocking";
  /** 缺口、冲突或不确定内容。 */
  summary: string;
  /** 相关来源。 */
  source_ref_ids: string[];
  /** Coordinator 或后续 Agent 的下一步。 */
  next_step: string;
}

/** Researcher 将外部输入清理成 Scout 内部 BDD 验证输入后的领域产物。 */
export interface ResearchArtifact {
  /** 固定为 ResearchArtifact。 */
  artifact_type: "ResearchArtifact";
  /** artifact schema 版本。 */
  artifact_version: number;
  /** run 内 artifact ID。 */
  artifact_id: string;
  /** run id。 */
  run_id: string;
  /** Researcher task id。 */
  task_id: string;
  /** Researcher 产物状态。 */
  status: "complete" | "prompt_required" | "insufficient_evidence" | "blocked" | "failed";
  /** 输入摘要。 */
  input_summary: string;
  /** 清理后的 BDD 事实。 */
  bdd_facts: BddFacts;
  /** 来源目录。 */
  source_refs: SourceRef[];
  /** 研究阶段形成的证据候选。 */
  evidence_refs: EvidenceRef[];
  /** 支撑研究过程的活动记录。 */
  activity_refs?: ActivityRef[];
  /** Verifier 可用的实现线索。 */
  implementation_hints: ImplementationHint[];
  /** 不确定项和缺口。 */
  uncertainty_items: UncertaintyItem[];
  /** 重放上下文。 */
  replay_context: ReplayContext;
}
