// Generated by schemas/domain/validation/generate-domain-validation.ts from schemas/domain/validation/*.yaml.
// Do not edit this file by hand.

import type { ArtifactRef, EvidenceRef, ValidationAgentRole, ValidationTaskStatus } from "./common.generated.js";
import type { ValidationGateStatus } from "./validation-result.generated.js";

export type ValidationDomainState =
  | "missing_bdd"
  | "research_required"
  | "research_running"
  | "research_ready"
  | "verification_required"
  | "verification_running"
  | "verification_complete"
  | "validation_required"
  | "validation_running"
  | "accepted"
  | "needs_fix"
  | "insufficient_evidence"
  | "blocked"
  | "failed"
;

export type ValidationCoordinatorAction =
  | "request_bdd"
  | "dispatch_researcher"
  | "dispatch_verifier"
  | "dispatch_validator"
  | "send_message"
  | "request_user_input"
  | "synthesize"
  | "stop"
;

/** Coordinator 可观察到的 worker 业务 outcome。 */
export interface WorkerOutcomeObservation {
  /** task id。 */
  task_id: string;
  /** worker role。 */
  agent_role: ValidationAgentRole;
  /** TaskResult 状态。 */
  status: ValidationTaskStatus;
  /** worker 结论摘要。 */
  summary: string;
  /** worker 提交的 artifact refs。 */
  artifact_refs: ArtifactRef[];
  /** worker 提交的 evidence refs。 */
  evidence_refs: EvidenceRef[];
  /** 阻塞原因。 */
  blocker?: string;
  /** worker 建议下一步。 */
  next_step?: string;
  /** Coordinator 观察时间。 */
  observed_at: string;
}

/** Coordinator 可观察到的用户输入事件。 */
export interface UserInputObservation {
  /** 用户输入事件 ID。 */
  input_id: string;
  /** 用户输入类型。 */
  kind: "bdd" | "clarification" | "confirmation" | "correction" | "other";
  /** 输入摘要。 */
  summary: string;
  /** 如果用户输入被登记为证据，对应 evidence refs。 */
  evidence_ref_ids?: string[];
  /** 观察时间。 */
  observed_at: string;
}

/** 业务状态流转记录。 */
export interface ValidationStateTransition {
  /** 流转前状态。 */
  from_state: ValidationDomainState;
  /** 流转后状态。 */
  to_state: ValidationDomainState;
  /** Coordinator 采取或应该采取的策略动作。 */
  action: ValidationCoordinatorAction;
  /** 状态变化原因。 */
  reason: string;
  /** 支撑该状态流转的 evidence refs。 */
  evidence_ref_ids: string[];
  /** 支撑该状态流转的 artifact refs。 */
  artifact_ref_ids: string[];
  /** 流转时间。 */
  occurred_at: string;
}

/** Coordinator 观察业务状态的快照；不包含 worker 私有推理过程。 */
export interface ValidationStateSnapshot {
  /** 固定为 ValidationStateSnapshot。 */
  artifact_type: "ValidationStateSnapshot";
  /** snapshot schema 版本。 */
  artifact_version: number;
  /** snapshot ID。 */
  snapshot_id: string;
  /** run id。 */
  run_id: string;
  /** 当前业务状态。 */
  current_state: ValidationDomainState;
  /** 当前状态下 Coordinator 可以采取的动作。 */
  allowed_actions: ValidationCoordinatorAction[];
  /** 已纳入状态判断的用户输入。 */
  user_inputs: UserInputObservation[];
  /** 已纳入状态判断的 worker outcomes。 */
  worker_outcomes: WorkerOutcomeObservation[];
  /** 当前状态可见 artifact refs。 */
  artifact_refs: ArtifactRef[];
  /** 当前状态可见 evidence refs。 */
  evidence_refs: EvidenceRef[];
  /** 最近一次 Validator gate 状态。 */
  latest_gate_status?: ValidationGateStatus;
  /** 已发生的业务状态流转。 */
  transitions: ValidationStateTransition[];
  /** 当前阻塞原因。 */
  blocker?: string;
  /** Coordinator 下一步策略。 */
  next_step: string;
}
