// Generated by schemas/domain/validation/generate-domain-validation.ts from schemas/domain/validation/*.yaml.
// Do not edit this file by hand.

import { readFileSync } from "node:fs";
import type { ResearchArtifact } from "./research-artifact.generated.js";
import type { ValidationStateSnapshot } from "./state.generated.js";
import type { ValidationResult } from "./validation-result.generated.js";
import type { VerificationReport } from "./verification-report.generated.js";

type FieldSchema = Readonly<{
  type: string;
  required: boolean;
  description?: string;
}>;

type DeclarationSchema = Readonly<{
  kind: "enum" | "interface" | "inline_object";
  description?: string;
  values?: readonly string[];
  fields?: Readonly<Record<string, FieldSchema>>;
}>;

export const domainValidationRuntimeSchema = {
  "ValidationAgentRole": {
    "kind": "enum",
    "values": [
      "coordinator",
      "researcher",
      "verifier",
      "validator"
    ]
  },
  "ValidationTaskStatus": {
    "kind": "enum",
    "values": [
      "complete",
      "prompt_required",
      "confirmation_required",
      "blocked",
      "insufficient_evidence",
      "failed"
    ]
  },
  "ValidationArtifactType": {
    "kind": "enum",
    "values": [
      "ResearchArtifact",
      "VerificationReport",
      "ValidationResult",
      "ValidationStateSnapshot"
    ]
  },
  "ValidationLocator": {
    "kind": "inline_object",
    "description": "可审计定位信息；用于把来源、证据或 artifact 定位到稳定对象。",
    "fields": {
      "kind": {
        "type": "\"file\" | \"line_range\" | \"heading\" | \"json_path\" | \"symbol\" | \"command\" | \"artifact\" | \"user_confirmation\" | \"other\"",
        "required": true,
        "description": "定位类型。"
      },
      "value": {
        "type": "string",
        "required": true,
        "description": "定位值，例如相对路径、json path、symbol、命令或用户确认 ID。"
      },
      "description": {
        "type": "string",
        "required": false,
        "description": "定位说明。"
      }
    }
  },
  "ArtifactRef": {
    "kind": "interface",
    "description": "领域 artifact 引用；Coordinator 只通过 refs 观察业务产物。",
    "fields": {
      "artifact_ref_id": {
        "type": "string",
        "required": true,
        "description": "run 内 artifact 引用 ID。"
      },
      "artifact_type": {
        "type": "ValidationArtifactType",
        "required": true,
        "description": "artifact 类型。"
      },
      "uri": {
        "type": "string",
        "required": true,
        "description": "artifact 路径、运行时 URI 或相对路径。"
      },
      "agent_role": {
        "type": "ValidationAgentRole",
        "required": true,
        "description": "产出该 artifact 的 agent role。"
      },
      "task_id": {
        "type": "string",
        "required": true,
        "description": "产出该 artifact 的 task id。"
      },
      "produced_at": {
        "type": "string",
        "required": true,
        "description": "产出时间。"
      },
      "digest": {
        "type": "string",
        "required": false,
        "description": "可选内容摘要，用于重放时检测漂移。"
      }
    }
  },
  "SourceRef": {
    "kind": "interface",
    "description": "领域来源引用；保留可审计来源，不复制来源全文。",
    "fields": {
      "source_ref_id": {
        "type": "string",
        "required": true,
        "description": "run 内来源 ID。"
      },
      "type": {
        "type": "\"bdd\" | \"knowledge\" | \"codebase\" | \"source\" | \"artifact\" | \"tool_output\" | \"user_confirmation\" | \"runtime\" | \"other\"",
        "required": true,
        "description": "来源类型。"
      },
      "collection_method": {
        "type": "\"file-read\" | \"knowledge-read\" | \"jarvis-codebase\" | \"codegraph\" | \"rg-fallback\" | \"tool-call\" | \"user-confirmation\" | \"runtime-event\" | \"other\"",
        "required": true,
        "description": "本 run 内来源收集方式。"
      },
      "ref": {
        "type": "string",
        "required": true,
        "description": "来源系统内稳定引用，例如 scenario_id、知识库文件、repo 名或 task id。"
      },
      "uri": {
        "type": "string",
        "required": true,
        "description": "来源 URI、路径或本地相对路径。"
      },
      "locator": {
        "type": "ValidationLocator",
        "required": true,
        "description": "来源内定位。"
      },
      "summary": {
        "type": "string",
        "required": true,
        "description": "来源摘要。"
      }
    }
  },
  "ActivityRef": {
    "kind": "interface",
    "description": "Runtime 观察到的活动引用；只能作为 evidence candidate。",
    "fields": {
      "activity_ref_id": {
        "type": "string",
        "required": true,
        "description": "run 内 activity ID。"
      },
      "type": {
        "type": "\"tool_call\" | \"command\" | \"file_read\" | \"file_write\" | \"mcp\" | \"plan\" | \"progress\" | \"runtime_event\" | \"other\"",
        "required": true,
        "description": "活动类型。"
      },
      "ref": {
        "type": "string",
        "required": true,
        "description": "工具名、命令、runtime event id 或日志 ref。"
      },
      "summary": {
        "type": "string",
        "required": true,
        "description": "该活动说明发生了什么。"
      },
      "observed_at": {
        "type": "string",
        "required": true,
        "description": "Runtime 观察时间。"
      }
    }
  },
  "EvidenceRef": {
    "kind": "interface",
    "description": "可支撑 Validation State 的证据引用；必须能追溯来源或活动。",
    "fields": {
      "evidence_ref_id": {
        "type": "string",
        "required": true,
        "description": "run 内 evidence ID。"
      },
      "type": {
        "type": "\"bdd\" | \"knowledge\" | \"code\" | \"config\" | \"log\" | \"artifact\" | \"tool_output\" | \"user_confirmation\" | \"gap\" | \"other\"",
        "required": true,
        "description": "证据类型。"
      },
      "ref": {
        "type": "string",
        "required": true,
        "description": "证据稳定引用。"
      },
      "summary": {
        "type": "string",
        "required": true,
        "description": "证据摘要。"
      },
      "locator": {
        "type": "ValidationLocator",
        "required": false,
        "description": "证据内定位。"
      },
      "source_ref_ids": {
        "type": "string[]",
        "required": true,
        "description": "支撑该证据的 SourceRef IDs。"
      },
      "activity_ref_ids": {
        "type": "string[]",
        "required": false,
        "description": "该证据来自哪些 Runtime activity；activity 不能单独替代证据解释。"
      }
    }
  },
  "ReplayContext": {
    "kind": "interface",
    "description": "重放上下文；用于复现同一 BDD 在同一知识库、代码库和 asset commit 下的判断。",
    "fields": {
      "run_id": {
        "type": "string",
        "required": true,
        "description": "当前 run id。"
      },
      "asset_commit_id": {
        "type": "string",
        "required": true,
        "description": "当前 agent mount 的 asset commit id。"
      },
      "agent_profile": {
        "type": "string",
        "required": true,
        "description": "agent profile 或 role。"
      },
      "knowledge_roots": {
        "type": "string[]",
        "required": true,
        "description": "本次使用的知识库根。"
      },
      "codebase_refs": {
        "type": "string[]",
        "required": true,
        "description": "本次涉及的 codebase repo/version/branch 摘要。"
      },
      "commands": {
        "type": "string[]",
        "required": true,
        "description": "影响领域结论的关键命令。"
      }
    }
  },
  "BddStatement": {
    "kind": "inline_object",
    "description": "BDD Given / When / Then 的单条语义。",
    "fields": {
      "text": {
        "type": "string",
        "required": true,
        "description": "BDD 语句文本。"
      },
      "source_ref_ids": {
        "type": "string[]",
        "required": true,
        "description": "支撑该语句的来源。"
      }
    }
  },
  "BddFacts": {
    "kind": "inline_object",
    "description": "Researcher 清理后的 BDD 输入。",
    "fields": {
      "scenario_id": {
        "type": "string",
        "required": true,
        "description": "BDD 场景 ID；无法唯一识别时不能 complete。"
      },
      "title": {
        "type": "string",
        "required": false,
        "description": "场景标题。"
      },
      "given": {
        "type": "BddStatement[]",
        "required": true,
        "description": "Given 语句。"
      },
      "when": {
        "type": "BddStatement[]",
        "required": true,
        "description": "When 语句。"
      },
      "then": {
        "type": "BddStatement[]",
        "required": true,
        "description": "Then 语句。"
      },
      "acceptance_criteria": {
        "type": "BddStatement[]",
        "required": false,
        "description": "额外验收条件。"
      }
    }
  },
  "ImplementationHint": {
    "kind": "interface",
    "description": "Verifier 后续可使用的实现定位线索；不是最终代码证据。",
    "fields": {
      "hint_id": {
        "type": "string",
        "required": true,
        "description": "hint ID。"
      },
      "kind": {
        "type": "\"repo\" | \"path\" | \"symbol\" | \"config\" | \"log\" | \"artifact\" | \"other\"",
        "required": true,
        "description": "线索类型。"
      },
      "ref": {
        "type": "string",
        "required": true,
        "description": "repo、路径、symbol、配置 key 或 artifact ref。"
      },
      "summary": {
        "type": "string",
        "required": true,
        "description": "为什么该线索可能有助于验证。"
      },
      "source_ref_ids": {
        "type": "string[]",
        "required": true,
        "description": "线索来源。"
      }
    }
  },
  "UncertaintyItem": {
    "kind": "interface",
    "description": "当前研究阶段无法闭环的不确定项。",
    "fields": {
      "item_id": {
        "type": "string",
        "required": true,
        "description": "不确定项 ID。"
      },
      "severity": {
        "type": "\"info\" | \"warning\" | \"blocking\"",
        "required": true,
        "description": "对后续验证的影响等级。"
      },
      "summary": {
        "type": "string",
        "required": true,
        "description": "缺口、冲突或不确定内容。"
      },
      "source_ref_ids": {
        "type": "string[]",
        "required": true,
        "description": "相关来源。"
      },
      "next_step": {
        "type": "string",
        "required": true,
        "description": "Coordinator 或后续 Agent 的下一步。"
      }
    }
  },
  "ResearchArtifact": {
    "kind": "interface",
    "description": "Researcher 将外部输入清理成 Scout 内部 BDD 验证输入后的领域产物。",
    "fields": {
      "artifact_type": {
        "type": "\"ResearchArtifact\"",
        "required": true,
        "description": "固定为 ResearchArtifact。"
      },
      "artifact_version": {
        "type": "number",
        "required": true,
        "description": "artifact schema 版本。"
      },
      "artifact_id": {
        "type": "string",
        "required": true,
        "description": "run 内 artifact ID。"
      },
      "run_id": {
        "type": "string",
        "required": true,
        "description": "run id。"
      },
      "task_id": {
        "type": "string",
        "required": true,
        "description": "Researcher task id。"
      },
      "status": {
        "type": "\"complete\" | \"prompt_required\" | \"insufficient_evidence\" | \"blocked\" | \"failed\"",
        "required": true,
        "description": "Researcher 产物状态。"
      },
      "input_summary": {
        "type": "string",
        "required": true,
        "description": "输入摘要。"
      },
      "bdd_facts": {
        "type": "BddFacts",
        "required": true,
        "description": "清理后的 BDD 事实。"
      },
      "source_refs": {
        "type": "SourceRef[]",
        "required": true,
        "description": "来源目录。"
      },
      "evidence_refs": {
        "type": "EvidenceRef[]",
        "required": true,
        "description": "研究阶段形成的证据候选。"
      },
      "activity_refs": {
        "type": "ActivityRef[]",
        "required": false,
        "description": "支撑研究过程的活动记录。"
      },
      "implementation_hints": {
        "type": "ImplementationHint[]",
        "required": true,
        "description": "Verifier 可用的实现线索。"
      },
      "uncertainty_items": {
        "type": "UncertaintyItem[]",
        "required": true,
        "description": "不确定项和缺口。"
      },
      "replay_context": {
        "type": "ReplayContext",
        "required": true,
        "description": "重放上下文。"
      }
    }
  },
  "CriterionVerdict": {
    "kind": "enum",
    "values": [
      "verified",
      "not_verified",
      "insufficient_evidence",
      "blocked"
    ]
  },
  "EvidenceSupportLevel": {
    "kind": "enum",
    "values": [
      "direct",
      "indirect",
      "partial",
      "contradictory",
      "missing"
    ]
  },
  "EvidenceMatrixItem": {
    "kind": "interface",
    "description": "单条 BDD Then 或验收条件的证据矩阵项。",
    "fields": {
      "criterion_id": {
        "type": "string",
        "required": true,
        "description": "验收条件 ID。"
      },
      "criterion_text": {
        "type": "string",
        "required": true,
        "description": "验收条件文本。"
      },
      "verdict": {
        "type": "CriterionVerdict",
        "required": true,
        "description": "该条件的验证结论。"
      },
      "support_level": {
        "type": "EvidenceSupportLevel",
        "required": true,
        "description": "证据支持程度。"
      },
      "evidence_ref_ids": {
        "type": "string[]",
        "required": true,
        "description": "支撑该结论的 evidence IDs。"
      },
      "gap_summary": {
        "type": "string",
        "required": false,
        "description": "证据不足或阻塞原因。"
      }
    }
  },
  "CodeEvidence": {
    "kind": "interface",
    "description": "源码证据；必须保留 repo/version/relative path/locator。",
    "fields": {
      "code_evidence_id": {
        "type": "string",
        "required": true,
        "description": "code evidence ID。"
      },
      "repo": {
        "type": "string",
        "required": true,
        "description": "codebase repo 名。"
      },
      "version": {
        "type": "string",
        "required": true,
        "description": "branch、tag、commit 或 SDK version。"
      },
      "relative_path": {
        "type": "string",
        "required": true,
        "description": "相对 codebase 根的路径。"
      },
      "locator": {
        "type": "string",
        "required": true,
        "description": "行号、symbol、json path 或其它定位。"
      },
      "symbol": {
        "type": "string",
        "required": false,
        "description": "相关 symbol。"
      },
      "collection_method": {
        "type": "\"codegraph\" | \"rg-fallback\" | \"file-read\" | \"other\"",
        "required": true,
        "description": "收集方式。"
      },
      "command": {
        "type": "string",
        "required": true,
        "description": "产生该定位的关键命令。"
      },
      "evidence_ref_id": {
        "type": "string",
        "required": true,
        "description": "对应 EvidenceRef。"
      },
      "summary": {
        "type": "string",
        "required": true,
        "description": "源码证据摘要，不复制长源码。"
      }
    }
  },
  "VerificationReport": {
    "kind": "interface",
    "description": "Verifier 对 BDD 进行证据验证后的领域产物。",
    "fields": {
      "artifact_type": {
        "type": "\"VerificationReport\"",
        "required": true,
        "description": "固定为 VerificationReport。"
      },
      "artifact_version": {
        "type": "number",
        "required": true,
        "description": "artifact schema 版本。"
      },
      "artifact_id": {
        "type": "string",
        "required": true,
        "description": "run 内 artifact ID。"
      },
      "run_id": {
        "type": "string",
        "required": true,
        "description": "run id。"
      },
      "task_id": {
        "type": "string",
        "required": true,
        "description": "Verifier task id。"
      },
      "status": {
        "type": "\"verified\" | \"not_verified\" | \"insufficient_evidence\" | \"blocked\" | \"failed\"",
        "required": true,
        "description": "Verifier 结论状态。"
      },
      "bdd_ref": {
        "type": "BddFacts",
        "required": true,
        "description": "被验证的 BDD。"
      },
      "research_artifact_refs": {
        "type": "ArtifactRef[]",
        "required": true,
        "description": "使用的 ResearchArtifact refs。"
      },
      "source_refs": {
        "type": "SourceRef[]",
        "required": true,
        "description": "来源目录。"
      },
      "evidence_refs": {
        "type": "EvidenceRef[]",
        "required": true,
        "description": "证据目录。"
      },
      "activity_refs": {
        "type": "ActivityRef[]",
        "required": false,
        "description": "关键活动引用。"
      },
      "evidence_matrix": {
        "type": "EvidenceMatrixItem[]",
        "required": true,
        "description": "每条验收条件对应的证据与结论。"
      },
      "code_evidence": {
        "type": "CodeEvidence[]",
        "required": true,
        "description": "源码证据。"
      },
      "knowledge_evidence_ref_ids": {
        "type": "string[]",
        "required": true,
        "description": "知识库 evidence refs。"
      },
      "gaps_and_risks": {
        "type": "UncertaintyItem[]",
        "required": true,
        "description": "缺口和风险。"
      },
      "replay_context": {
        "type": "ReplayContext",
        "required": true,
        "description": "重放上下文。"
      }
    }
  },
  "ValidationGateStatus": {
    "kind": "enum",
    "values": [
      "accepted",
      "needs_fix",
      "insufficient_evidence",
      "blocked",
      "failed"
    ]
  },
  "ValidationFinding": {
    "kind": "interface",
    "description": "Validator 对字段、证据、状态或重放条件的发现。",
    "fields": {
      "finding_id": {
        "type": "string",
        "required": true,
        "description": "finding ID。"
      },
      "severity": {
        "type": "\"info\" | \"warning\" | \"error\" | \"blocking\"",
        "required": true,
        "description": "严重程度。"
      },
      "category": {
        "type": "\"schema\" | \"required_field\" | \"evidence_ref\" | \"state_consistency\" | \"replay\" | \"risk\" | \"other\"",
        "required": true,
        "description": "发现类别。"
      },
      "ref": {
        "type": "string",
        "required": true,
        "description": "artifact 字段、证据 ref 或状态 ref。"
      },
      "summary": {
        "type": "string",
        "required": true,
        "description": "问题或确认摘要。"
      },
      "evidence_ref_ids": {
        "type": "string[]",
        "required": false,
        "description": "支撑该 finding 的证据。"
      },
      "minimum_fix": {
        "type": "string",
        "required": false,
        "description": "不合格时的最小修复项。"
      }
    }
  },
  "ValidationResult": {
    "kind": "interface",
    "description": "Validator gate 结果；决定 artifact 是否可被 Coordinator 用于推进状态。",
    "fields": {
      "artifact_type": {
        "type": "\"ValidationResult\"",
        "required": true,
        "description": "固定为 ValidationResult。"
      },
      "artifact_version": {
        "type": "number",
        "required": true,
        "description": "artifact schema 版本。"
      },
      "artifact_id": {
        "type": "string",
        "required": true,
        "description": "run 内 artifact ID。"
      },
      "run_id": {
        "type": "string",
        "required": true,
        "description": "run id。"
      },
      "task_id": {
        "type": "string",
        "required": true,
        "description": "Validator task id。"
      },
      "gate_status": {
        "type": "ValidationGateStatus",
        "required": true,
        "description": "gate 结论。"
      },
      "checked_artifact_refs": {
        "type": "ArtifactRef[]",
        "required": true,
        "description": "被检查的 artifact refs。"
      },
      "source_refs": {
        "type": "SourceRef[]",
        "required": true,
        "description": "Validator 使用的来源。"
      },
      "evidence_refs": {
        "type": "EvidenceRef[]",
        "required": true,
        "description": "Validator 使用或确认的证据。"
      },
      "findings": {
        "type": "ValidationFinding[]",
        "required": true,
        "description": "所有字段、证据、状态和重放发现。"
      },
      "minimum_fixes": {
        "type": "string[]",
        "required": true,
        "description": "gate 未通过时的最小修复项。"
      },
      "replay_context": {
        "type": "ReplayContext",
        "required": true,
        "description": "重放上下文。"
      }
    }
  },
  "ValidationDomainState": {
    "kind": "enum",
    "values": [
      "missing_bdd",
      "research_required",
      "research_running",
      "research_ready",
      "verification_required",
      "verification_running",
      "verification_complete",
      "validation_required",
      "validation_running",
      "accepted",
      "needs_fix",
      "insufficient_evidence",
      "blocked",
      "failed"
    ]
  },
  "ValidationCoordinatorAction": {
    "kind": "enum",
    "values": [
      "request_bdd",
      "dispatch_researcher",
      "dispatch_verifier",
      "dispatch_validator",
      "send_message",
      "request_user_input",
      "synthesize",
      "stop"
    ]
  },
  "WorkerOutcomeObservation": {
    "kind": "interface",
    "description": "Coordinator 可观察到的 worker 业务 outcome。",
    "fields": {
      "task_id": {
        "type": "string",
        "required": true,
        "description": "task id。"
      },
      "agent_role": {
        "type": "ValidationAgentRole",
        "required": true,
        "description": "worker role。"
      },
      "status": {
        "type": "ValidationTaskStatus",
        "required": true,
        "description": "TaskResult 状态。"
      },
      "summary": {
        "type": "string",
        "required": true,
        "description": "worker 结论摘要。"
      },
      "artifact_refs": {
        "type": "ArtifactRef[]",
        "required": true,
        "description": "worker 提交的 artifact refs。"
      },
      "evidence_refs": {
        "type": "EvidenceRef[]",
        "required": true,
        "description": "worker 提交的 evidence refs。"
      },
      "blocker": {
        "type": "string",
        "required": false,
        "description": "阻塞原因。"
      },
      "next_step": {
        "type": "string",
        "required": false,
        "description": "worker 建议下一步。"
      },
      "observed_at": {
        "type": "string",
        "required": true,
        "description": "Coordinator 观察时间。"
      }
    }
  },
  "UserInputObservation": {
    "kind": "interface",
    "description": "Coordinator 可观察到的用户输入事件。",
    "fields": {
      "input_id": {
        "type": "string",
        "required": true,
        "description": "用户输入事件 ID。"
      },
      "kind": {
        "type": "\"bdd\" | \"clarification\" | \"confirmation\" | \"correction\" | \"other\"",
        "required": true,
        "description": "用户输入类型。"
      },
      "summary": {
        "type": "string",
        "required": true,
        "description": "输入摘要。"
      },
      "evidence_ref_ids": {
        "type": "string[]",
        "required": false,
        "description": "如果用户输入被登记为证据，对应 evidence refs。"
      },
      "observed_at": {
        "type": "string",
        "required": true,
        "description": "观察时间。"
      }
    }
  },
  "ValidationStateTransition": {
    "kind": "interface",
    "description": "业务状态流转记录。",
    "fields": {
      "from_state": {
        "type": "ValidationDomainState",
        "required": true,
        "description": "流转前状态。"
      },
      "to_state": {
        "type": "ValidationDomainState",
        "required": true,
        "description": "流转后状态。"
      },
      "action": {
        "type": "ValidationCoordinatorAction",
        "required": true,
        "description": "Coordinator 采取或应该采取的策略动作。"
      },
      "reason": {
        "type": "string",
        "required": true,
        "description": "状态变化原因。"
      },
      "evidence_ref_ids": {
        "type": "string[]",
        "required": true,
        "description": "支撑该状态流转的 evidence refs。"
      },
      "artifact_ref_ids": {
        "type": "string[]",
        "required": true,
        "description": "支撑该状态流转的 artifact refs。"
      },
      "occurred_at": {
        "type": "string",
        "required": true,
        "description": "流转时间。"
      }
    }
  },
  "ValidationStateSnapshot": {
    "kind": "interface",
    "description": "Coordinator 观察业务状态的快照；不包含 worker 私有推理过程。",
    "fields": {
      "artifact_type": {
        "type": "\"ValidationStateSnapshot\"",
        "required": true,
        "description": "固定为 ValidationStateSnapshot。"
      },
      "artifact_version": {
        "type": "number",
        "required": true,
        "description": "snapshot schema 版本。"
      },
      "snapshot_id": {
        "type": "string",
        "required": true,
        "description": "snapshot ID。"
      },
      "run_id": {
        "type": "string",
        "required": true,
        "description": "run id。"
      },
      "current_state": {
        "type": "ValidationDomainState",
        "required": true,
        "description": "当前业务状态。"
      },
      "allowed_actions": {
        "type": "ValidationCoordinatorAction[]",
        "required": true,
        "description": "当前状态下 Coordinator 可以采取的动作。"
      },
      "user_inputs": {
        "type": "UserInputObservation[]",
        "required": true,
        "description": "已纳入状态判断的用户输入。"
      },
      "worker_outcomes": {
        "type": "WorkerOutcomeObservation[]",
        "required": true,
        "description": "已纳入状态判断的 worker outcomes。"
      },
      "artifact_refs": {
        "type": "ArtifactRef[]",
        "required": true,
        "description": "当前状态可见 artifact refs。"
      },
      "evidence_refs": {
        "type": "EvidenceRef[]",
        "required": true,
        "description": "当前状态可见 evidence refs。"
      },
      "latest_gate_status": {
        "type": "ValidationGateStatus",
        "required": false,
        "description": "最近一次 Validator gate 状态。"
      },
      "transitions": {
        "type": "ValidationStateTransition[]",
        "required": true,
        "description": "已发生的业务状态流转。"
      },
      "blocker": {
        "type": "string",
        "required": false,
        "description": "当前阻塞原因。"
      },
      "next_step": {
        "type": "string",
        "required": true,
        "description": "Coordinator 下一步策略。"
      }
    }
  }
} as const satisfies Readonly<Record<string, DeclarationSchema>>;

const schema: Readonly<Record<string, DeclarationSchema>> = domainValidationRuntimeSchema;

export type DomainValidationArtifact =
  | ResearchArtifact
  | VerificationReport
  | ValidationResult
  | ValidationStateSnapshot;

export function validateDomainValidationArtifact(value: unknown): string[] {
  const type = readArtifactType(value);
  if (!type) return ["domain validation artifact must contain artifact_type."];
  return validateDomainValidationValue(value, type);
}

export function validateDomainValidationValue(value: unknown, type: string): string[] {
  const errors: string[] = [];
  validateType(value, type, type, errors);
  if (errors.length === 0) validateDomainSemanticConstraints(value, type, errors);
  return errors;
}

export function createDomainValidationSkeleton(type: string): unknown {
  return createSkeletonForDeclaration(type);
}

function readArtifactType(value: unknown): string | undefined {
  if (!isRecord(value)) return undefined;
  if (typeof value.artifact_type === "string") return value.artifact_type;
  return undefined;
}

function validateDomainSemanticConstraints(value: unknown, type: string, errors: string[]): void {
  if (type === "ResearchArtifact") validateResearchArtifact(value, errors);
  if (type === "VerificationReport") validateVerificationReport(value, errors);
  if (type === "ValidationResult") validateValidationResult(value, errors);
  if (type === "ValidationStateSnapshot") validateValidationStateSnapshot(value, errors);
}

function validateResearchArtifact(value: unknown, errors: string[]): void {
  if (!isRecord(value)) return;
  const status = value.status;
  const bdd = value.bdd_facts;
  if (status === "complete") {
    if (!isRecord(bdd) || !hasNonEmptyArray(bdd.given) || !hasNonEmptyArray(bdd.when) || !hasNonEmptyArray(bdd.then)) {
      errors.push("ResearchArtifact complete requires non-empty bdd_facts.given/when/then.");
    }
    if (!hasNonEmptyArray(value.source_refs)) {
      errors.push("ResearchArtifact complete requires source_refs.");
    }
  }
}

function validateVerificationReport(value: unknown, errors: string[]): void {
  if (!isRecord(value)) return;
  if (value.status === "verified") {
    if (!hasNonEmptyArray(value.evidence_matrix)) {
      errors.push("VerificationReport verified requires evidence_matrix.");
    }
    if (!hasNonEmptyArray(value.evidence_refs)) {
      errors.push("VerificationReport verified requires evidence_refs.");
    }
  }
  const evidenceRefIds = collectStringIds(value.evidence_refs, "evidence_ref_id");
  if (Array.isArray(value.evidence_matrix)) {
    for (const [index, item] of value.evidence_matrix.entries()) {
      if (!isRecord(item)) continue;
      if ((item.verdict === "verified" || item.verdict === "not_verified") && !hasNonEmptyArray(item.evidence_ref_ids)) {
        errors.push(`VerificationReport.evidence_matrix[${index}] requires evidence_ref_ids for verdict ${String(item.verdict)}.`);
      }
      validateIdRefs(item.evidence_ref_ids, evidenceRefIds, `VerificationReport.evidence_matrix[${index}].evidence_ref_ids`, errors);
    }
  }
  if (Array.isArray(value.code_evidence)) {
    for (const [index, item] of value.code_evidence.entries()) {
      if (!isRecord(item)) continue;
      validateIdRefs([item.evidence_ref_id], evidenceRefIds, `VerificationReport.code_evidence[${index}].evidence_ref_id`, errors);
    }
  }
}

function validateValidationResult(value: unknown, errors: string[]): void {
  if (!isRecord(value)) return;
  if (value.gate_status === "accepted" && !hasNonEmptyArray(value.checked_artifact_refs)) {
    errors.push("ValidationResult accepted requires checked_artifact_refs.");
  }
  if (value.gate_status !== "accepted" && !hasNonEmptyArray(value.minimum_fixes)) {
    errors.push("ValidationResult non-accepted gate requires minimum_fixes.");
  }
}

function validateValidationStateSnapshot(value: unknown, errors: string[]): void {
  if (!isRecord(value)) return;
  if (value.current_state === "accepted") {
    if (value.latest_gate_status !== "accepted") {
      errors.push("ValidationStateSnapshot accepted requires latest_gate_status accepted.");
    }
    if (!hasNonEmptyArray(value.artifact_refs) || !hasNonEmptyArray(value.evidence_refs)) {
      errors.push("ValidationStateSnapshot accepted requires artifact_refs and evidence_refs.");
    }
  }
  if ((value.current_state === "blocked" || value.current_state === "failed") && typeof value.blocker !== "string") {
    errors.push("ValidationStateSnapshot blocked/failed requires blocker.");
  }
}

function createSkeletonForDeclaration(name: string): unknown {
  const declaration = schema[name];
  if (!declaration) throw new Error(`Unknown domain validation declaration: ${name}`);
  if (declaration.kind === "enum") return declaration.values?.[0] ?? "";

  const result: Record<string, unknown> = {};
  for (const [fieldName, field] of Object.entries(declaration.fields ?? {})) {
    if (field.required) result[fieldName] = createSkeletonForType(field.type);
  }
  return result;
}

function createSkeletonForType(type: string): unknown {
  const arrayElementType = readArrayElementType(type);
  if (arrayElementType) return [];

  const literalOptions = readLiteralOptions(type);
  if (literalOptions.length > 0) return literalOptions[0];

  if (type === "string") return "";
  if (type === "number") return 0;
  if (type === "boolean") return false;
  if (schema[type]) return createSkeletonForDeclaration(type);

  throw new Error(`Unsupported domain validation skeleton type: ${type}`);
}

function validateType(value: unknown, type: string, path: string, errors: string[]): void {
  const arrayElementType = readArrayElementType(type);
  if (arrayElementType) {
    if (!Array.isArray(value)) {
      errors.push(`${path} must be an array.`);
      return;
    }
    for (const [index, item] of value.entries()) validateType(item, arrayElementType, `${path}[${index}]`, errors);
    return;
  }

  const literalOptions = readLiteralOptions(type);
  if (literalOptions.length > 0) {
    if (!literalOptions.includes(value as string | number | boolean)) {
      errors.push(`${path} must be ${formatOptions(literalOptions)}.`);
    }
    return;
  }

  if (type === "string") {
    if (typeof value !== "string" || value.length === 0) errors.push(`${path} must be a non-empty string.`);
    return;
  }
  if (type === "number") {
    if (typeof value !== "number" || !Number.isFinite(value)) errors.push(`${path} must be a finite number.`);
    return;
  }
  if (type === "boolean") {
    if (typeof value !== "boolean") errors.push(`${path} must be a boolean.`);
    return;
  }

  const declaration = schema[type];
  if (!declaration) {
    errors.push(`${path} uses unknown domain validation schema type ${type}.`);
    return;
  }

  if (declaration.kind === "enum") {
    if (typeof value !== "string" || !(declaration.values ?? []).includes(value)) {
      errors.push(`${path} must be one of ${formatOptions(declaration.values ?? [])}.`);
    }
    return;
  }

  if (!isRecord(value)) {
    errors.push(`${path} must be an object.`);
    return;
  }

  for (const [fieldName, field] of Object.entries(declaration.fields ?? {})) {
    const fieldPath = `${path}.${fieldName}`;
    if (!(fieldName in value)) {
      if (field.required) errors.push(`${fieldPath} is required.`);
      continue;
    }
    const fieldValue = value[fieldName];
    if (fieldValue === undefined) {
      if (field.required) errors.push(`${fieldPath} is required.`);
      continue;
    }
    validateType(fieldValue, field.type, fieldPath, errors);
  }
}

function collectStringIds(value: unknown, key: string): Set<string> {
  const ids = new Set<string>();
  if (!Array.isArray(value)) return ids;
  for (const item of value) {
    if (!isRecord(item)) continue;
    const id = item[key];
    if (typeof id === "string" && id.trim().length > 0) ids.add(id);
  }
  return ids;
}

function validateIdRefs(value: unknown, ids: Set<string>, path: string, errors: string[]): void {
  const refs = Array.isArray(value) ? value : [value];
  for (const ref of refs) {
    if (typeof ref !== "string" || ref.trim().length === 0) continue;
    if (!ids.has(ref)) errors.push(`${path} references unknown id ${ref}.`);
  }
}

function hasNonEmptyArray(value: unknown): boolean {
  return Array.isArray(value) && value.length > 0;
}

function readArrayElementType(type: string): string | undefined {
  return type.endsWith("[]") ? type.slice(0, -2) : undefined;
}

function readLiteralOptions(type: string): Array<string | number | boolean> {
  const parts = type.split("|").map((part) => part.trim());
  const literals = parts.map(readLiteralOption);
  return literals.every((literal) => literal !== undefined)
    ? literals as Array<string | number | boolean>
    : [];
}

function readLiteralOption(type: string): string | number | boolean | undefined {
  if ((type.startsWith('"') && type.endsWith('"')) || (type.startsWith("'") && type.endsWith("'"))) return type.slice(1, -1);
  if (/^-?\d+(?:\.\d+)?$/.test(type)) return Number(type);
  if (type === "true") return true;
  if (type === "false") return false;
  return undefined;
}

function formatOptions(values: readonly unknown[]): string {
  return values.map((value) => JSON.stringify(value)).join(" | ");
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function runCli(): void {
  const filePath = process.argv[2];
  if (!filePath) {
    process.stderr.write("Usage: validation.generated.js <domain-validation-artifact.json>\n");
    process.exitCode = 1;
    return;
  }
  const parsed = JSON.parse(readFileSync(filePath, "utf8")) as unknown;
  const errors = validateDomainValidationArtifact(parsed);
  if (errors.length > 0) {
    process.stderr.write(errors.join("\n") + "\n");
    process.exitCode = 1;
    return;
  }
  process.stdout.write(JSON.stringify({ status: "passed", filePath }, null, 2) + "\n");
}

if (process.argv[1]?.endsWith("validation.generated.js")) runCli();
