// Generated by schemas/domain/validation/generate-domain-validation.ts from schemas/domain/validation/*.yaml.
// Do not edit this file by hand.

import type { ActivityRef, ArtifactRef, EvidenceRef, ReplayContext, SourceRef } from "./common.generated.js";
import type { BddFacts, UncertaintyItem } from "./research-artifact.generated.js";

export type CriterionVerdict =
  | "verified"
  | "not_verified"
  | "insufficient_evidence"
  | "blocked"
;

export type EvidenceSupportLevel =
  | "direct"
  | "indirect"
  | "partial"
  | "contradictory"
  | "missing"
;

/** 单条 BDD Then 或验收条件的证据矩阵项。 */
export interface EvidenceMatrixItem {
  /** 验收条件 ID。 */
  criterion_id: string;
  /** 验收条件文本。 */
  criterion_text: string;
  /** 该条件的验证结论。 */
  verdict: CriterionVerdict;
  /** 证据支持程度。 */
  support_level: EvidenceSupportLevel;
  /** 支撑该结论的 evidence IDs。 */
  evidence_ref_ids: string[];
  /** 证据不足或阻塞原因。 */
  gap_summary?: string;
}

/** 源码证据；必须保留 repo/version/relative path/locator。 */
export interface CodeEvidence {
  /** code evidence ID。 */
  code_evidence_id: string;
  /** codebase repo 名。 */
  repo: string;
  /** branch、tag、commit 或 SDK version。 */
  version: string;
  /** 相对 codebase 根的路径。 */
  relative_path: string;
  /** 行号、symbol、json path 或其它定位。 */
  locator: string;
  /** 相关 symbol。 */
  symbol?: string;
  /** 收集方式。 */
  collection_method: "codegraph" | "rg-fallback" | "file-read" | "other";
  /** 产生该定位的关键命令。 */
  command: string;
  /** 对应 EvidenceRef。 */
  evidence_ref_id: string;
  /** 源码证据摘要，不复制长源码。 */
  summary: string;
}

/** Verifier 对 BDD 进行证据验证后的领域产物。 */
export interface VerificationReport {
  /** 固定为 VerificationReport。 */
  artifact_type: "VerificationReport";
  /** artifact schema 版本。 */
  artifact_version: number;
  /** run 内 artifact ID。 */
  artifact_id: string;
  /** run id。 */
  run_id: string;
  /** Verifier task id。 */
  task_id: string;
  /** Verifier 结论状态。 */
  status: "verified" | "not_verified" | "insufficient_evidence" | "blocked" | "failed";
  /** 被验证的 BDD。 */
  bdd_ref: BddFacts;
  /** 使用的 ResearchArtifact refs。 */
  research_artifact_refs: ArtifactRef[];
  /** 来源目录。 */
  source_refs: SourceRef[];
  /** 证据目录。 */
  evidence_refs: EvidenceRef[];
  /** 关键活动引用。 */
  activity_refs?: ActivityRef[];
  /** 每条验收条件对应的证据与结论。 */
  evidence_matrix: EvidenceMatrixItem[];
  /** 源码证据。 */
  code_evidence: CodeEvidence[];
  /** 知识库 evidence refs。 */
  knowledge_evidence_ref_ids: string[];
  /** 缺口和风险。 */
  gaps_and_risks: UncertaintyItem[];
  /** 重放上下文。 */
  replay_context: ReplayContext;
}
