// Generated by schemas/input/scripts/generate-validation-body.ts from schemas/input/validation-body/*.yaml.
// Do not edit this file by hand.

export * from "./validation-body/source-ref.generated.js";
export * from "./validation-body/catalog.generated.js";
export * from "./validation-body/bdd-fact.generated.js";
export * from "./validation-body/capability-fact.generated.js";
export * from "./validation-body/requirement-fact.generated.js";
export * from "./validation-body/specification-fact.generated.js";
export * from "./validation-body/feature-fact.generated.js";
export * from "./validation-body/implementation-fact.generated.js";
export * from "./validation-body/body.generated.js";
export * from "./validation-body/validation.generated.js";
